name: power_of_one_basketball
description: "Power of One Basketball player stat tracking application"
publish_to: 'none'
version: 1.2.0

flutter_localization:
  sdk: ">=3.2.0-0 <4.0.0"
# environment:
#   sdk: ">=3.2.0-0 <4.0.0"
environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  #external packages
  flutter_neumorphic: ^3.2.0
  firebase_core: ^3.13.0

  firebase_auth: ^5.5.2
  firebase_crashlytics: ^4.3.5
  # cloud_firestore: "^2.4.0"
  # cloud_functions: "^3.0.0"
  # firebase_storage: "^10.0.1"
  # firebase_messaging: "^10.0.4"
  # firebase_remote_config: "^0.10.0+3"
  # Updated to work with new core only plugins (no new changes):
  # firebase_admob: "^"
  firebase_analytics: ^11.4.5
  firebase_database: ^11.3.5
  # firebase_dynamic_links: "^2.0.10"
  # firebase_in_app_messaging: "^0.5.0"
  firebase_performance: ^0.10.1+5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  provider: ^6.0.5
  google_fonts: ^6.2.1
  animations: ^2.0.1
  styled_widget: ^0.4.1
  introduction_screen: ^3.1.4
  dots_indicator: ^4.0.1
  crypto: ^3.0.1
  flutter_hooks: ^0.21.2
  flutter_animate: ^4.2.0+1
  flutter_keyboard_visibility: ^6.0.0
  flutter_spinkit: ^5.2.1

  #In app purchases
  in_app_purchase: ^3.1.12
  purchases_flutter: ^8.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  patrol: ^3.5.1

flutter:
  uses-material-design: true

  assets:
  - assets/images/
